name: AWS SAM CI/CD with Local Testing

on:
  push:
    branches: [main, staging]

env:
  AWS_REGION: us-east-1
  STACK_NAME: cicd-test

jobs:
  local-test:
    name: Run Local Tests with SAM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Install test dependencies
        working-directory: ./src
        run: npm install

      - name: Start local API (background)
        run: sam local start-api &
        env:
          DOCKER_LAMBDA_USE_STDIN: 1

      - name: Wait for API to be ready
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:3000/employer-login && break || sleep 3
          done

      - name: Run integration tests
        working-directory: ./src
        run: npm run test:local

  deploy:
    name: Deploy SAM
    runs-on: ubuntu-latest
    needs: local-test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM
        run: sam build

      - name: Deploy SAM
        run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
