name: AWS SAM CI/CD with Postman

on:
  push:
    branches:
      - main
      - staging

env:
  AWS_REGION: us-east-1
  STACK_NAME: cicd-test

jobs:
  build-deploy:
    name: Build & Deploy SAM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app
        run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Get API Gateway URL
        id: get-api-url
        run: |
          URL=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
            --output text)
          echo "api_url=$URL" >> $GITHUB_OUTPUT

  postman-test:
    name: Run Postman Tests
    runs-on: ubuntu-latest
    needs: build-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Create Postman environment with API URL
        run: |
          mkdir -p tests
          sed "s|{{api_url}}|${{ needs.build-deploy.outputs.api_url }}|g" tests/environment.template.json > tests/environment.json

      - name: Run Postman Tests with Newman
        run: |
          newman run tests/CI-CD.postman_collection.json \
            --environment tests/environment.json \
            --reporters cli,json \
            --reporter-json-export tests/report.json

      - name: Upload Postman Test Report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: postman-report
          path: tests/report.json
