name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build with SAM
        run: sam build

      - name: Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1 # change as needed
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name my-lambda-stack \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --resolve-s3
