name: Test and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd src
          npm install

      - name: Install Newman
        run: npm install -g newman

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build with SAM
        run: sam build

      - name: Start local API (background)
        run: |
          sam local start-api &
          sleep 10  # give time to boot up

      - name: Run Postman tests locally
        run: |
          newman run tests/CI-CD.postman_collection.json \
            -e tests/local-environment.postman_environment.json \
            --bail

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda (staging)
        run: |
          sam deploy --config-env staging --no-confirm-changeset --no-fail-on-empty-changeset
