name: SAM Pre-Deploy Testing

on:
  push:
    branches: [main, staging]

env:
  AWS_REGION: us-east-1
  STACK_NAME: cicd-test

jobs:
  predeploy-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set up AWS CLI & SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM
        run: sam build

      - name: Start local API & Run Tests
        run: |
          sam local start-api &
          sleep 10 # wait for API to boot
          npm run test:local
        timeout-minutes: 2

      - name: Deploy (only if tests pass)
        run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
