name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd src
          npm install

      - name: Install Newman
        run: |
          npm install -g newman

      - name: List test files
        run: |
          ls -la tests

      - name: Run Postman tests/CI-CD.postman_collection.json
        run: |
          newman run tests
      - name: Debug: List files in tests folder
          run: ls -l tests

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build with SAM
        run: sam build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with SAM
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
